### ISSUE TITLE
Erro with torchpie packet

### ISSUE THREAD

**Issue by santyelegy** [chuangg/Foley-Music#1]
I get the following erro:
Traceback (most recent call last):
  File "/disk/11811901/anaconda3/envs/torchb/python3.7/site-packages/injector/__init__.py", line 804, in get
    return self._context[key]
KeyError: <class 'torchpie.core.environment.Args'>

and a exception occur when handling this exception
packages/torchpie/core/environment/__init__.py", line 112, in provide_args
    args = Args()
  File "/disk/11811901/anaconda3/envs/torch/lib/python3.7/site-packages/torchpie/core/environment/__init__.py", line 75, in __init__
    self.parse_known_args_from(parser)
AttributeError: 'Args' object has no attribute 'parse_known_args_from'

I get my torchpie packet by running `pip install -r requirements.txt` and train the URMP by `CUDA_VISIBLE_DEVICES=6 python train.py -c config/URMP/violin.conf -e exps/urmp-vn`  with torch version 1.4

I check my version of torchpie,it seems that it do not have `parse_known_args_from`, and I only find few message about this packet from google.

**Comment by Negiinnn** [comment]
Hi @santyelegy Were you able to solve this issue? I am getting the same error.

**Comment by santyelegy** [comment]
> Hi @santyelegy Were you able to solve this issue? I am getting the same error.

@Negiinnn I try to remove the torchpie packet, but I can not reach the acc in the paper, so I think I made some mistake when refactoring,and I'm here to seek for the author's help. my fork is [here](https://github.com/santyelegy/Foley-Music-1) , it can run on my server.

**Comment by SunDoge** [comment]
@santyelegy @Negiinnn 
```bash
pip install typed-args==0.2
```

**Comment by Negiinnn** [comment]
Thank you!
